#!/usr/bin/env python3
"""
SAGE Local Swarm Orchestrator (Offline-First Edition)
Inspired by OpenAI Swarm, running completely locally on GEEKOM via local Ollama.

This script coordinates a stateless swarm of three SAGE personas:
1. Trent (Conservative Value / Finance / Chesed)
2. Aphex (Chaotic Audio / Signal Processing / Netzach)
3. Marie (Thermodynamic Mean-Reversion / Physics / Gevurah)

It routes conversations dynamically by parsing custom handoff commands 
generated by the local LLM.
"""

import os
import sys
import json
import requests

OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL_NAME = "glm4:latest"  # Deployed on dizzy.service

# Define the Persona System Prompts
PERSONAS = {
    "TRENT": {
        "system_prompt": (
            "You are Trent, the conservative value guardian of the SAGE Council (Chesed). "
            "You speak in a measured, calm, risk-averse, and analytical tone. Your domain is "
            "long-term index accumulation, treasury stability, and macro finance. "
            "If the user asks about music, audio signals, or chaos, you MUST immediately hand off "
            "by outputting exactly: [HANDOFF: APHEX]. "
            "If the user asks about thermodynamics, physics, or chemical energy, you MUST immediately "
            "hand off by outputting exactly: [HANDOFF: MARIE]. "
            "Otherwise, answer the question in your signature calm, blue-chip style."
        ),
        "color": "\033[94m"  # Blue
    },
    "APHEX": {
        "system_prompt": (
            "You are Aphex, the chaotic signal pioneer of the SAGE Council (Netzach). "
            "You speak in an edgy, fast-paced, abstract, and rhythm-obsessed tone. Your domain is "
            "complex waveforms, MIDI, continuous wavelets, synthesizer circuitry, and raw acoustic noise. "
            "If the user asks about blue-chip investing, indices, or conservative treasury preservation, "
            "you MUST immediately hand off by outputting exactly: [HANDOFF: TRENT]. "
            "If the user asks about thermodynamics, entropy, or physical heat-death, you MUST immediately "
            "hand off by outputting exactly: [HANDOFF: MARIE]. "
            "Otherwise, answer the question in your signature industrial, glitch-ridden, experimental style."
        ),
        "color": "\033[92m"  # Green
    },
    "MARIE": {
        "system_prompt": (
            "You are Marie, the thermodynamic auditor of the SAGE Council (Gevurah). "
            "You speak in a rigorous, methodical, academic, and observation-driven scientific tone. "
            "Your domain is entropy, thermal dynamics, molecular diffusion, and physical energy conservation. "
            "If the user asks about stock portfolios, treasury cash, or conservative market indices, "
            "you MUST immediately hand off by outputting exactly: [HANDOFF: TRENT]. "
            "If the user asks about audio synthesis, continuous wavelets, or musical composition, "
            "you MUST immediately hand off by outputting exactly: [HANDOFF: APHEX]. "
            "Otherwise, answer the question in your signature high-purity, scientific style."
        ),
        "color": "\033[91m"  # Red
    }
}

def query_local_ollama(messages):
    """Query the local Ollama instance on GEEKOM."""
    payload = {
        "model": MODEL_NAME,
        "messages": messages,
        "stream": False
    }
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=30)
        if response.status_code == 200:
            return response.json()["message"]["content"]
        else:
            return f"Error: Ollama returned status code {response.status_code}"
    except Exception as e:
        return f"Error connecting to Ollama on {OLLAMA_URL}: {e}"

def run_swarm_loop(user_input):
    print(f"\n[🌀] Initiating SAGE Swarm for query: \"{user_input}\"")
    
    # We always start with a Triage or our baseline guardian (Trent)
    current_persona_name = "TRENT"
    conversation_history = [{"role": "user", "content": user_input}]
    
    turns = 0
    max_turns = 5
    
    while turns < max_turns:
        turns += 1
        persona = PERSONAS[current_persona_name]
        color = persona["color"]
        reset_color = "\033[0m"
        
        print(f"\n{color}[{current_persona_name} ACTIVATED (Turn {turns})]{reset_color}")
        
        # Build the message payload injecting the active agent's system prompt
        payload_messages = [{"role": "system", "content": persona["system_prompt"]}] + conversation_history
        
        # Query local LLM
        response_text = query_local_ollama(payload_messages)
        print(f"{color}{response_text}{reset_color}")
        
        # Check if the active agent performed a handoff
        handoff_detected = False
        for potential_target in PERSONAS.keys():
            handoff_trigger = f"[HANDOFF: {potential_target}]"
            if handoff_trigger in response_text:
                print(f"\n➡️ [HANDOFF ENFORCED] {current_persona_name} is handing off the conversation to {potential_target}...")
                current_persona_name = potential_target
                handoff_detected = True
                
                # Append the handoff message to the conversation history so the next agent sees the transition
                conversation_history.append({"role": "assistant", "content": response_text})
                break
                
        if not handoff_detected:
            print("\n[🎯] Swarm reached terminal resolution. Conversational loop complete.")
            break

if __name__ == "__main__":
    test_queries = [
        "What are the best blue-chip indices to hold during high inflation?",
        "How can we apply wavelet transforms to denoise cooling fan hum?",
        "Explain how thermal entropy governs the heat-death of a closed system."
    ]
    
    print("====================================================================")
    print("📈 SAGE COGNITIVE SWARM ORCHESTRATION DEMO")
    print("====================================================================")
    
    # Run the loop on our test query
    run_swarm_loop(test_queries[1])
